<a href="https://colab.research.google.com/github/10dimensions/gnc-toolbox/blob/main/quaternion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
from scipy.spatial.transform import Rotation as R

In [6]:
def demonstrate_quaternion_rotation():
    print("--- GNC Quaternion Rotation Utility ---\n")

    # =========================================================================
    # 1. Define the initial vector (Camera Boresight in Body Frame)
    # =========================================================================
    # Pointing straight down the -Z axis
    v_body = np.array([0.0, 0.0, -1.0])
    print(f"1. Initial Vector (Body Frame): {v_body}")

    # =========================================================================
    # 2. Define the Quaternion Rotation
    # =========================================================================
    # Let's rotate the spacecraft 90 degrees around the Y-axis (Pitch up).
    # Math: theta = 90 deg.
    # w = cos(45 deg) = 0.707
    # x, y, z = sin(45 deg) * [0, 1, 0] = [0, 0.707, 0]

    # IMPORTANT: SciPy expects quaternions in [x, y, z, w] format!
    theta_rad = np.radians(90.0)
    q_scipy = np.array([
        0.0,                  # x
        np.sin(theta_rad/2),  # y
        0.0,                  # z
        np.cos(theta_rad/2)   # w
    ])

    print(f"2. Quaternion [x,y,z,w]: {np.round(q_scipy, 3)}")
    print(f"   Quaternion Norm: {np.linalg.norm(q_scipy):.4f} (Must be 1.0)")

    # =========================================================================
    # 3. Apply the Rotation using SciPy
    # =========================================================================
    # Create the Rotation object from the quaternion
    rot = R.from_quat(q_scipy)

    # Apply the rotation to our vector
    v_rotated = rot.apply(v_body)

    print(f"\n3. Rotated Vector (New Body Frame): {np.round(v_rotated, 3)}")
    print("   -> The camera, originally pointing -Z, is now pointing -X!")

    # =========================================================================
    # 4. Bonus: Convert to DCM to prove it matches Day 2's math!
    # =========================================================================
    dcm = rot.as_matrix()
    print(f"\n4. Equivalent DCM:\n{np.round(dcm, 3)}")

In [7]:
if __name__ == "__main__":
    demonstrate_quaternion_rotation()

--- GNC Quaternion Rotation Utility ---

1. Initial Vector (Body Frame): [ 0.  0. -1.]
2. Quaternion [x,y,z,w]: [0.    0.707 0.    0.707]
   Quaternion Norm: 1.0000 (Must be 1.0)

3. Rotated Vector (New Body Frame): [-1.  0. -0.]
   -> The camera, originally pointing -Z, is now pointing -X!

4. Equivalent DCM:
[[ 0.  0.  1.]
 [ 0.  1.  0.]
 [-1.  0.  0.]]
